namespace Assets.Resources.Scripts.Web
{
    public enum GameWebMediaHeader
    {
        ApplicationJavascript,
        ApplicationJson,
        ApplicationXWwwFormUrlEncoded,
        ApplicationXml,
        ApplicationZip,
        ApplicationPdf,
        ApplicationSql,
        ApplicationGraphql,
        ApplicationLdJson,
        ApplicationDoc,
        ApplicationDocx,
        ApplicationXls,
        ApplicationXlsx,
        ApplicationPpt,
        ApplicationPptx,
        ApplicationOdt,
        ApplicationVndApiJson,
        AudioMpeg,
        AudioOgg,
        MultipartFormData,
        TextCss,
        TextHtml,
        TextXml,
        TextCsv,
        TextPlain,
        ImagePng,
        ImageJpeg,
        ImageGif
    }
}